name: multi_toolbox
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  url_launcher: ^6.2.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1" 
  flutter_native_splash: "^2.3.11" 

flutter:
  uses-material-design: true

  # Declaración de la carpeta de imágenes
  assets:
    - assets/images/

# CONFIGURACIÓN DEL ICONO DEL LANZADOR (MISMO NIVEL QUE 'flutter:')
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/mi_foto1.png"
  
  # Usaremos adaptive_icon_background para asegurar que el círculo se vea más limpio en Android
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/images/mi_foto1.png"

# CONFIGURACIÓN DEL SPLASH SCREEN (MISMO NIVEL QUE 'flutter:')
flutter_native_splash:
  # El fondo del splash será blanco para que se parezca al predeterminado de Flutter
  color: "#FFFFFF" 
  
  # Tu foto como imagen central del splash
  image: "assets/images/mi_foto1.png" 
  
  # Para que la foto se vea grande en el centro, el paquete la escalará.
  # Si quieres el círculo, asegúrate de que mi_foto1.png sea circular con fondo transparente.
  android: true
  ios: true